[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c3 --log-format defmt"

[env]
# DEFMT_LOG="info"
DEFMT_LOG = "embassy_net=warn,info"
ESPFLASH_BAUD='921600'

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
  "-Z", "stack-protector=all",
]

target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
